# Generated by Django 4.2.4 on 2023-08-31 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField(blank=True, null=True)),
                ('prefijo_cuil', models.IntegerField(blank=True, null=True)),
                ('sufijo_cuil', models.IntegerField(blank=True, null=True)),
                ('cod_area', models.IntegerField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
                ('localidad', models.CharField(blank=True, max_length=60, null=True)),
                ('provincia', models.CharField(blank=True, max_length=60, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=60, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('estado_civil', models.CharField(blank=True, max_length=40, null=True)),
                ('imprime_estado_civil', models.BooleanField(default=True)),
                ('cantidad_hijos', models.CharField(blank=True, default='0', max_length=10, null=True)),
                ('imprime_cantidad_hijos', models.BooleanField(default=True)),
                ('editar_cv', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto', models.CharField(blank=True, max_length=180, null=True)),
                ('month_inicio', models.CharField(blank=True, max_length=2, null=True)),
                ('year_inicio', models.CharField(blank=True, max_length=4, null=True)),
                ('month_fin', models.CharField(blank=True, max_length=2, null=True)),
                ('year_fin', models.CharField(blank=True, max_length=4, null=True)),
                ('referencia_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_puesto', models.CharField(blank=True, max_length=180, null=True)),
                ('referencia_cod_area', models.CharField(blank=True, max_length=5, null=True)),
                ('referencia_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('trabaja_actualmente', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('duracion', models.CharField(blank=True, max_length=30, null=True)),
                ('year_egreso', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(blank=True, max_length=80, null=True)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('year_inicio', models.CharField(blank=True, max_length=4, null=True)),
                ('year_fin', models.CharField(blank=True, max_length=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvs_app.status')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cvs_app.academic_level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='About_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(blank=True, max_length=500, null=True)),
                ('objetivo_imp', models.BooleanField(default=True)),
                ('aptitudes', models.CharField(blank=True, max_length=500, null=True)),
                ('aptitudes_imp', models.BooleanField(default=True)),
                ('habilidades', models.CharField(blank=True, max_length=500, null=True)),
                ('habilidades_imp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
